name: Windows

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        haxe-version: [4.0.5, 4.1.5, 4.2.2]

    steps:
    - uses: actions/checkout@v1
    - uses: egor-tensin/vs-shell@v2
    - name: Setup Haxe (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Setup app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        WXWIN: D:\a\hxWidgets\hxWidgets\wxWidgets-3.1.3
      run: |
        choco install wget --no-progress
        wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
        7z x wxWidgets-3.1.3.tar.bz2
        7z x wxWidgets-3.1.3.tar
        cd wxWidgets-3.1.3
        cd build
        cd msw
        copy D:\a\hxWidgets\hxWidgets\wxWidgets-3.1.3\include\msvc\wx\setup.h D:\a\hxWidgets\hxWidgets\wxWidgets-3.1.3\include\wx\setup.h
        copy D:\a\hxWidgets\hxWidgets\wxWidgets-3.1.3\include\msvc\wx\setup.h D:\a\hxWidgets\hxWidgets\wxWidgets-3.1.3\lib\vc_dll\mswu\wx\setup.h
        nmake.exe -f makefile.vc BUILD=release RUNTIME_LIBS=static SHARED=0
        cd ..
        cd ..
        cd ..
        dir
        haxelib install hxcpp --always --quiet
        haxelib install hscript --always --quiet
        haxelib dev hxWidgets .
        
    - name: Build app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      env:
        WXWIN: D:\a\hxWidgets\hxWidgets\wxWidgets-3.1.3
      run: |
        cd samples\00-Showcase
        haxe build.hxml

