name: OSX

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        haxe-version: [3.4.7, 4.0.5, 4.1.5, 4.2.2]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Haxe (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Setup app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        brew update
        brew install wxwidgets
        brew uninstall libjpeg --ignore-dependencies
        brew install libjpeg
        wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
        tar xjf wxWidgets-3.1.3.tar.bz2
        cd wxWidgets-3.1.3
        ./configure --with-opengl --disable-shared > log.txt
        sudo make
        sudo make install
        echo ::add-path::$(pwd)
        cd ..
        haxelib install hxcpp --always --quiet
        haxelib install hscript --always --quiet
        haxelib dev hxWidgets .

    - name: Build app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        cd samples/00-Showcase
        haxe build.hxml
